### ISSUE TITLE
improvement for wtd.table

### ISSUE THREAD

**Issue by tyner** [harrelfe/Hmisc#13]
Currenntly, only one Inf (of each sign) is allowed:

     > wtd.table(c(-Inf, 1), c(1, 1))
     $x
     [1] -Inf    1
     
     $sum.of.weights
     [1] 1 1

but

     > wtd.table(c(-Inf, -Inf, 1), c(1, 1, 1))
     Error in if (any(diff(x) == 0)) { : missing value where TRUE/FALSE needed

The fix would be to use:

     if (any(duplicated(x))) {

instead.

Regards,
Ben

**Comment by tyner** [comment]
I noticed that Hmisc depends on survival >= 2.37-6, which itself depends on R >= 2.13.0, so I think that means we can safely switch over to `anyDuplicated(x)`.

**Comment by harrelfe** [comment]
Thanks for catching that.  Done.
Frank


On 04/20/2015 08:45 AM, Benjamin Tyner wrote:
>
> I noticed that Hmisc depends on survival >= 2.37-6, which itself 
> depends on R >= 2.13.0, so I think that means we can safely switch 
> over to |anyDuplicated(x)|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/13#issuecomment-94455292>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*
