### ISSUE TITLE
Function for weighted standard error?

### ISSUE THREAD

**Issue by brshallo** [harrelfe/Hmisc#138]
Would adding a function for weighted standard error be useful? Something based on:
![image](https://user-images.githubusercontent.com/30487784/106687279-d30a4780-6599-11eb-883c-cf3c78b521c0.png)
-[wikipedia, weighted arithmetic mean](https://en.wikipedia.org/wiki/Weighted_arithmetic_mean#Statistical_properties)

For example along the lines of:
```r
wtd.stderror <- function(x, weights){
  var <- Hmisc::wtd.var(x, weights)
  weights <- sum( (weights / sum(weights))^2 )
  
  sqrt(var*weights)
}
```

However [this SO conversation](https://stats.stackexchange.com/questions/25895/computing-standard-error-in-weighted-mean-estimation) suggests that generally computing a weighted standard error in such a way may not be a good idea.

**Comment by harrelfe** [comment]
I'm not sure.   I don't use weights enough to know.
