### ISSUE TITLE
Incorrect big.mark in the df.format

### ISSUE THREAD

**Issue by jkomelj** [harrelfe/Hmisc#142]
In my country, the default is dec.mark="," and big.mark=".", but the function format.df does not work correct, if called with these parameters. Doing some minor changes in it, e.g. dec.mark=getOption("OutDec"), I was able to fix it for my needs. But whatever I try, big.mark in the result is always a comma instead of dot. However, formatting the data frame column by column with other functions, I can bypass the problem, but it would be nice, if format.df could be used. I mainly use the latex function. It is great. Thank you.

Janez Komelj, Slovenia

An example:

require(Hmisc)
A <- data.frame(a=c(123456.12345,654321.987654),b=c(654321.987654,123456.12345))
B <- format.df(A,cdec=c(2,3),dec.mark=",",big.mark=".")

**Comment by harrelfe** [comment]
I changed format.df to use `OutDec` when `cdot` is not specified.   This should fix it.  Thanks.

**Comment by jkomelj** [comment]
Thank you!

**Comment by jkomelj** [comment]
The function format.df still changes the optional parameter big.mark="." in decimal.mark. It is changed by the formt function.

 

  formt <- function(x, decimal.mark='.', nsmall=0,

                    scientific=c(-4,4), digits=NULL, na.blank=FALSE, ...) {

    y <- format(x, nsmall=nsmall, decimal.mark=decimal.mark,

                digits=digits, ...)

    ###??? Is the replacement below necessary? If format.df is called with the

   ###??? optional parameter big.mark=".", it is not correct. In my case,

    ###??? the results are correct, if the line below is excluded.

    ###??? if(decimal.mark != '.') y <- gsub('\\.', decimal.mark, y)

    if(na.blank) y <- ifelse(is.na(x), '', y)

    y

 }
