### ISSUE TITLE
Question about power calculation using "popower" function 

### ISSUE THREAD

**Issue by Daphne2019** [harrelfe/Hmisc#149]
I was using "popower" function to calculate power for two-tailed two-sample comparison of ordinal endpoint, and I noticed that under the null hypothesis (odds ratio=1), power is 0.025 when type I error rate (alpha) = 0.05, and 0.012 when type I error rate (alpha) = 0.025:

> p1 <- c(.1,.2,.4,.3)
> popower(p = p1, odds.ratio = 1, n = 1000, alpha=0.05)
Power: 0.025
Efficiency of design compared with continuous response: 0.9
Approximate standard error of log odds ratio: 0.1156

> popower(p = p1, odds.ratio = 1, n = 1000, alpha=0.025)
Power: 0.012
Efficiency of design compared with continuous response: 0.9
Approximate standard error of log odds ratio: 0.1156

Excuse me if this is a silly question: 
I wonder why the power is not equal to alpha under the null hypothesis, but always half of alpha?

Any help with this would be greatly appreciated!

**Comment by harrelfe** [comment]
Power is (usually) inherently a one-sided issue.   When for example we compute power to detect a 10mmHg reduction in systolic blood pressure we don't give ourselves credit for occasionally getting a 10mmHg **increase**.
