### ISSUE TITLE
Namespace load failed

### ISSUE THREAD

**Issue by RogueMedic** [harrelfe/Hmisc#151]
Please excuse if this is a repeat of discussion I did not see it in the listings. 

Background: I am new to using R and I am attempting to load the 'Hmisc' package for a statistics class. I am running R 4.1.1  However it appears that the system begins to load appropriately but I receive the below notes:

> install.packages('Hmisc')
Warning in install.packages :
  unable to access index for repository https://www.stats.ox.ac.uk/pub/RWin/bin/macosx/contrib/4.1:
  cannot open URL 'https://www.stats.ox.ac.uk/pub/RWin/bin/macosx/contrib/4.1/PACKAGES'
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/Hmisc_4.6-0.tgz'
Content type 'application/x-gzip' length 3259927 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

and:
The downloaded binary packages are in
	/var/folders/yg/bm2yvjcd4m3c55ws6tzfssk40000gn/T//RtmppSURAG/downloaded_packages

If I attempt to load the library I receive:
> library(Hmisc)
Error: package or namespace load failed for ‘Hmisc’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’

fair warning I have next to zip on programing skills. I am a critical care paramedic and firefighter by nature so I am good with fixing broken people not computer systems. I will say I am sure there is a step I am missing but I cannot see it.

Any assistance would be most welcomed.

Thank you
AJ

**Comment by rhurlin** [comment]
Hi  @RogueMedic,
Just saw your problem. The error message when loading `library(Hmisc)` indicates that the package `stringi` is not present. This can be installed via `install.packages('stringi')` as already known from Hmisc.

After that `library(Hmisc)` should work, if no other packages are missing and have to be installed first ...
