### ISSUE TITLE
seqFreq is not exported

### ISSUE THREAD

**Issue by sepmein** [harrelfe/Hmisc#160]
https://github.com/harrelfe/Hmisc/blob/b80593b82ed0e6b12f8eab42156d8b7869dc1723/R/seqFreq.r#L11

It seems the roxygen2 doc of seqFreq function missing @export annotation.

When I ran `missChk` function, 
```R
# Error in seqFreq(adm0 = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,  : 
#  could not find function "seqFreq"
```

**Comment by harrelfe** [comment]
This was fixed in the last CRAN release.
