### ISSUE TITLE
hist.data.frame() with cex.axis, etc.

### ISSUE THREAD

**Issue by jinghuazhao** [harrelfe/Hmisc#168]
Hi Frank,

I tried to enlarge fonts in hist.data.frame() through cex.axis, cex.label, etc., but it appears with no effect -- by looking at the code, I am wondering if those hist() statements should take a (...) argument? When I did that it appears working but the y-axis is in Greek (still in need of figuring it out)!

Thanks very much for creating such a useful function.

Jing Hua Zhao

**Comment by jinghuazhao** [comment]
After adding (...), a call hist.data.frame(d,cex.axis=2.5,cex.lab=2.5,cex.mtext=2.5,cex.names=2.5,ylab=expression("Frequency")) appears fixing the y-axis label as well (I feel somewhat strange graphics::hist() takes a ylab with no default value in the documentation nevertheless permits a ylab= option).

**Comment by harrelfe** [comment]
I now prefer `ggplot2` for this after melting the dataset over all the variable of interest.  I think the output is neater.  But patches in `hist.data.frame` are welcomed.
