### ISSUE TITLE
html_describe_con CRAN NOTE: two internal helpers 'g' with different parameters

### ISSUE THREAD

**Issue by MichaelChirico** [harrelfe/Hmisc#177]
https://github.com/harrelfe/Hmisc/blob/46cb60b1672fef0f1afd66b7e5aab5d5715c2a14/R/describe.s#L1364
https://github.com/harrelfe/Hmisc/blob/46cb60b1672fef0f1afd66b7e5aab5d5715c2a14/R/describe.s#L1423

Seems like a false positive in `R CMD check` to me, but it's also a code smell (over-using uninformative variable names like `g`)

**Comment by harrelfe** [comment]
This is a longstanding (10 years?) false positive in the checking softrware.
