### ISSUE TITLE
Unable to set `probs` to a scalar value in `hdquantile`  

### ISSUE THREAD

**Issue by alihru** [harrelfe/Hmisc#179]
Hello! 

I encounter the following issue when using `hdquantile`: I would like to get the H-D estimate for a vector of losses `x` and a single quantile value (`probs` = 0.995). I.e. I'm trying to compute VaR99.5 for a given loss distribution, where VaR stands for Value-at-Risk. I get the following error message:

`
Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
  'dimnames' applied to non-array
`  

Essentially, it's problematic that `probs` is not a vector of length >= 2. As a result, if I want to use the function for one value only I can run it for quantile values I don't need or duplicate the required quantile value, resulting in time performance deterioration and code contamination. 

Thank you very much and looking forward to your response.

**Comment by couthcommander** [comment]
What version of Hmisc? This example works for me:
```
Hmisc::hdquantile(runif(1000), probs = 0.995, se = TRUE)
    0.995 
0.9919176 
attr(,"se")
      0.995 
0.001587465 
```

**Comment by couthcommander** [comment]
no response, assuming recent versions address this issue

**Comment by loopemperor** [comment]
The issue occurs when trying to get the weights. I'm on 5.1.1 and 
`Hmisc::hdquantile(runif(1000), probs = 0.995, weights = TRUE)`
results in an error
`Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
  'dimnames' applied to non-array`

**Comment by couthcommander** [comment]
Got it, can confirm. I've created a pull request to fix issue.
