### ISSUE TITLE
Hmisc package citation

### ISSUE THREAD

**Issue by UniAlberta** [harrelfe/Hmisc#187]
Hi, I used Hmisc pakage in late 2022 and 2023 for analyzing fungal communities. Unfortunately, I didn`t record the package version when I used it and now I need to mention it in my manuscript. Can you help me with that, please?

**Comment by UniAlberta** [comment]
Thank you so much! I mostly used it in 2023. Am I good to cite v 5.0?

**Comment by couthcommander** [comment]
Convention is the full version number so perhaps v5.1-0 (released 5/8/23)

**Comment by UniAlberta** [comment]
Thanks for your quick reply.
