### ISSUE TITLE
Error while reading a mdb database

### ISSUE THREAD

**Issue by janeshdev** [harrelfe/Hmisc#21]
I have downloaded the file to my local drive and tried opening it with microsoft access and works totally fine. However, when I used the Hmisc package using the following command, it throws an error `Error in system(paste("mdb-tables-1", file), intern = TRUE): 'mdb-tables' not found`. 

The code I used is 
`dd <- mdb.get("S:/Projects/pgd.mdb")`

Do you have any suggestions on how can I make it work ? Thanks.

**Comment by harrelfe** [comment]
How did you install the mdb-tools package on your operating system?


On 03/05/2015 11:58 AM, Janesh Devkota wrote:
>
> I have downloaded the file to my local drive and tried opening it with 
> microsoft access and works totally fine. However, when I used the 
> Hmisc package using the following command, it throws an error |Error 
> in system(paste("mdb-tables-1", file), intern = TRUE): 'mdb-tables' 
> not found|.
>
> The code I used is
> |dd <- mdb.get("S:/Projects/pgd.mdb")|
>
> Do you have any suggestions on how can I make it work ? Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/21>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by janeshdev** [comment]
I am not sure whether I installed mdb-tools package. I am using on windows 7. I did download the package but seems like it would only work for linux but I am not sure. Would you please give me some directions on how to install mdb-tools package on windows ? Thank you.

**Comment by harrelfe** [comment]
There would have to be an executable built especially for Windows. Since 
I use linux I'm not sure about whether that exists.
Frank

On 03/06/2015 04:40 PM, Janesh Devkota wrote:
>
> I am not sure whether I installed mdb-tools package. I am using on 
> windows 7. I did download the package but seems like it would only 
> work for linux but I am not sure. Would you please give me some 
> directions on how to install mdb-tools package on windows ? Thank you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/21#issuecomment-77649743>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by yikeshu0611** [comment]
mdb-tables.exe is provides here
https://github.com/lsgunth/mdbtools-win

**Comment by jijitoutou** [comment]
> mdb-tables.exe is provides here https://github.com/lsgunth/mdbtools-win

When I try to install the .exe, the system (Windows 11) shows an error "libmdb-3.dll cannot be found". How can I deal with this? Thank you.
