### ISSUE TITLE
Hmisc won't open get.spss in newest version of R

### ISSUE THREAD

**Issue by shecht1** [harrelfe/Hmisc#25]
The Hmisc library will not load ggplot2 properly.  I am unable to use get.spss command using Hmisc library.  This is a problem with the new R3.2.0 build.  It works perfectly using R3.1.3.

**Comment by harrelfe** [comment]
Send a reproducible example that fails.  Include any .Rprofile you have defined.  Include your operating system name.

On May 2, 2015 12:03 PM, shecht1 <notifications@github.com> wrote:

The Hmisc library will not load ggplot2 properly. I am unable to use get.spss command using Hmisc library. This is a problem with the new R3.2.0 build. It works perfectly using R3.1.3.

**Comment by shecht1** [comment]
It did not work on four different computers, but the older version did work just fine on all computers.   This computer is a windows enterprise 7.

**Comment by harrelfe** [comment]
It is extremely important that you send the information I requested.  
Please, please always send code and error messages when you report 
problems as serious as these (or even for trivial problems).  And send 
.Rprofile or any other code that is executed in the session.

I just installed R 3.2.0 and Hmisc 3.16-0 on a Windows 7 computer and am 
not having any difficulty running Hmisc or ggplots.


On 05/02/2015 09:16 PM, shecht1 wrote:
> It did not work on four different computers, but the older version did 
> work just fine on all computers. This computer is a windows enterprise 7.
>
> From: Frank Harrell [mailto:notifications@github.com]
> Sent: Saturday, May 02, 2015 3:42 PM
> To: harrelfe/Hmisc
> Cc: Steven Hecht
> Subject: Re: [Hmisc] Hmisc won't open get.spss in newest version of R 
> (#25)
>
> Send a reproducible example that fails. Include any .Rprofile you have 
> defined. Include your operating system name.
>
> On May 2, 2015 12:03 PM, shecht1 
> <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> The Hmisc library will not load ggplot2 properly. I am unable to use 
> get.spss command using Hmisc library. This is a problem with the new 
> R3.2.0 build. It works perfectly using R3.1.3.
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/harrelfe/Hmisc/issues/25>.
>
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/harrelfe/Hmisc/issues/25#issuecomment-98391340>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/25#issuecomment-98429302>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by shecht1** [comment]
Yep, I used spss.get.   I reloaded the newest version of R (3.2.0) and ran the Hmisc again so that you can see what’s happening.  .Rprofile is attached.

I obtained the Hmisc library from the first US site (US(CA1).  Do all mirror sites have the newest version of Hmisc (Hmisc 3.16-0).  Is there a command that I can use to find out the version of Hmisc I loaded on my machine?

I think below is everything you asked for in terms of showing all commands and errors:  Attached is the .Rprofile file.



R version 3.2.0 (2015-04-16) -- "Full of Ingredients"

Copyright (C) 2015 The R Foundation for Statistical Computing

Platform: i386-w64-mingw32/i386 (32-bit)



R is free software and comes with ABSOLUTELY NO WARRANTY.

You are welcome to redistribute it under certain conditions.

Type 'license()' or 'licence()' for distribution details.



R is a collaborative project with many contributors.

Type 'contributors()' for more information and

'citation()' on how to cite R or R packages in publications.



Type 'demo()' for some demos, 'help()' for on-line help, or

'help.start()' for an HTML browser interface to help.

Type 'q()' to quit R.



> install.packages("Hmisc", dependencies=TRUE)

Installing package into ‘C:/Users/shecht/Documents/R/win-library/3.2’

(as ‘lib’ is unspecified)

--- Please select a CRAN mirror for use in this session ---

trying URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/3.2/Hmisc_3.16-0.zip'

Content type 'application/zip' length 1612068 bytes (1.5 MB)

downloaded 1.5 MB



p



The downloaded binary packages are in

        C:\Users\shecht\AppData\Local\Temp\RtmpEtlflq\downloaded_packages

> library("Hmisc")

Loading required package: grid

Loading required package: lattice

Loading required package: survival

Loading required package: Formula

Loading required package: ggplot2

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :

  there is no package called ‘Rcpp’

Error: package ‘ggplot2’ could not be loaded

> library("Hmisc")

Loading required package: ggplot2

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :

  there is no package called ‘Rcpp’

Error: package ‘ggplot2’ could not be loaded

>

**Comment by geobrando** [comment]
@shecht1 This does not appear to be an Hmisc issue.  I did a quick search for this error and found several hits that could solve your problem.  Make sure you have 'Rcpp' installed.  Or try installing ggplot2 like this `install.packages("ggplot2", dependencies=TRUE)`

http://r.789695.n4.nabble.com/installing-Packages-td4702312.html

**Comment by shecht1** [comment]
Installing package Rcpp and then Hmisc enable ggplot2 to load in correctly when I loaded in Hmisc and I was able to get my spss file to work as well.  Thanks!   Evidently, this Rcpp library needs to be included as part of the Hmisc package or included as one of the “dependencies” when using the install.packages("Hmisc", dependencies=TRUE)
command.

**Comment by harrelfe** [comment]
Hmisc does not use Rcpp so there is another package with improper 
dependencies documented in its DESCRIPTION file.

On 05/07/2015 10:21 AM, shecht1 wrote:
> Installing package Rcpp and then Hmisc enable ggplot2 to load in 
> correctly when I loaded in Hmisc and I was able to get my spss file to 
> work as well. Thanks! Evidently, this Rcpp library needs to be 
> included as part of the Hmisc package or included as one of the 
> “dependencies” when using the install.packages("Hmisc", 
> dependencies=TRUE)
> command.
>
>
> From: Brandon Knight [mailto:notifications@github.com]
> Sent: Thursday, May 07, 2015 10:49 AM
> To: harrelfe/Hmisc
> Cc: Steven Hecht
> Subject: Re: [Hmisc] Hmisc won't open get.spss in newest version of R 
> (#25)
>
>
> @shecht1<https://github.com/shecht1> This does not appear to be an 
> Hmisc issue. I did a quick search for this error and found several 
> hits that could solve your problem. Make sure you have 'Rcpp' 
> installed. Or try installing ggplot2 like this 
> install.packages("ggplot2", dependencies=TRUE)
>
> http://r.789695.n4.nabble.com/installing-Packages-td4702312.html
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99895239>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99907843>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by shecht1** [comment]
Hmm, so what you are saying is that the Hmisc library at the mirror site I chose is including files in there that somehow is preventing ggplot2 from loading in properly.  GGplot would not load in properly until I first installed Rcpp….

**Comment by geobrando** [comment]
@shecht1 Again, your issue was with loading ggplot2 (a dependency of Hmisc) and not Hmisc itself.  If you would have tried to load ggplot2 with `library("ggplot2")` you would certainly have had the same problem.  Nothing to do with Hmisc.

**Comment by shecht1** [comment]
Yes, I know that.  GGplot2 not loading was the error I found.  The Rcpp file once loaded enabled the ggplot2 to load.  Am I correct in assuming that the GGplot2 library is where the get command for spss is “housed”??

**Comment by harrelfe** [comment]
You need to take a step backwards and seriously study R before asking 
that.  You need to understand the find and objects functions, for 
example.  You are confused about boundaries between packages. In 
particular, you used Hmisc so you could use spss.get.  They why conclude 
that spss.get has jumped packages?


On 05/07/2015 10:56 AM, shecht1 wrote:
> Yes, I know that. GGplot2 not loading was the error I found. The Rcpp 
> file once loaded enabled the ggplot2 to load. Am I correct in assuming 
> that the GGplot2 library is where the get command for spss is “housed”??
>
> From: Brandon Knight [mailto:notifications@github.com]
> Sent: Thursday, May 07, 2015 11:54 AM
> To: harrelfe/Hmisc
> Cc: Steven Hecht
> Subject: Re: [Hmisc] Hmisc won't open get.spss in newest version of R 
> (#25)
>
>
> @shecht1<https://github.com/shecht1> Again, your issue was with 
> loading ggplot2 (a dependency of Hmisc) and not Hmisc itself. If you 
> would have tried to load ggplot2 with library("ggplot2") you would 
> certainly have had the same problem. Nothing to do with Hmisc.
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99920620>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99921135>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by shecht1** [comment]
You comment is well taken.  I do not think anything jumped   The error message was:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called ‘Rcpp’
Error: package ‘ggplot2’ could not be loaded

Therefore, I am concluding that Hmisc could not load my spss file because a) Rcpp package was not loaded, b) ggplot2 was not loaded, or c) both were not loaded correctly.    In other words, Hmisc could not do its job because either Rcpp was not loaded or Ggplot2 or both.   No jump in my comments – sorry for the confusion..

**Comment by geobrando** [comment]
@shecht1 To answer your question, I suspect that the ggplot2 error was preventing Hmisc from loading at all.  You didn't provide full details of your issue, including **how** spss.get was failing (i.e. the error message).  All you said was that you were unable to use spss.get.

It's important that you provide all relevant details when filing a report.  But as a first step you should always search online for an easy answer.

**Comment by harrelfe** [comment]
Your conclusion as to the cause is incorrect.  This is not at all 
related to Hmisc.  Please see the note that another person posted about 
this today.


On 05/07/2015 11:05 AM, shecht1 wrote:
> You comment is well taken. I do not think anything jumped The error 
> message was:
>
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), 
> versionCheck = vI[[j]]) :
> there is no package called ‘Rcpp’
> Error: package ‘ggplot2’ could not be loaded
>
> Therefore, I am concluding that Hmisc could not load my spss file 
> because a) Rcpp package was not loaded, b) ggplot2 was not loaded, or 
> c) both were not loaded correctly. In other words, Hmisc could not do 
> its job because either Rcpp was not loaded or Ggplot2 or both. No jump 
> in my comments – sorry for the confusion..
>
>
>
> From: Frank Harrell [mailto:notifications@github.com]
> Sent: Thursday, May 07, 2015 12:02 PM
> To: harrelfe/Hmisc
> Cc: Steven Hecht
> Subject: Re: [Hmisc] Hmisc won't open get.spss in newest version of R 
> (#25)
>
> You need to take a step backwards and seriously study R before asking
> that. You need to understand the find and objects functions, for
> example. You are confused about boundaries between packages. In
> particular, you used Hmisc so you could use spss.get. They why conclude
> that spss.get has jumped packages?
>
>
> On 05/07/2015 10:56 AM, shecht1 wrote:
> > Yes, I know that. GGplot2 not loading was the error I found. The Rcpp
> > file once loaded enabled the ggplot2 to load. Am I correct in assuming
> > that the GGplot2 library is where the get command for spss is 
> “housed”??
> >
> > From: Brandon Knight [mailto:notifications@github.com]
> > Sent: Thursday, May 07, 2015 11:54 AM
> > To: harrelfe/Hmisc
> > Cc: Steven Hecht
> > Subject: Re: [Hmisc] Hmisc won't open get.spss in newest version of R
> > (#25)
> >
> >
> > @shecht1<https://github.com/shecht1> Again, your issue was with
> > loading ggplot2 (a dependency of Hmisc) and not Hmisc itself. If you
> > would have tried to load ggplot2 with library("ggplot2") you would
> > certainly have had the same problem. Nothing to do with Hmisc.
> >
> > —
> > Reply to this email directly or view it on
> > 
> GitHub<https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99920620>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99921135>.
> >
>
> -- 
> ------------------------------------------------------------------------
> Frank E Harrell Jr Professor and Chairman School of Medicine
>
> Department of *Biostatistics* *Vanderbilt University*
>
>
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99922221>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/25#issuecomment-99923185>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*

**Comment by shecht1** [comment]
All of your (and other’s) advice and comments are greatly appreciated.  I will take your and B Knight’s comments seriously and will comply.  With respect.  Steve
