### ISSUE TITLE
Unable to Install latest build of Hmisc package for  R 3.2.0

### ISSUE THREAD

**Issue by GitKlip** [harrelfe/Hmisc#26]
I was able to download and install all dependencies for Hmisc but when it came time to actually install Hmisc it failed.  I
R Version 3.2.0
RStudio Version 0.98.1091
no .Rprofile defined
OS: Windows 8.1

> install.packages("Hmisc",dependencies = TRUE)
Installing package into ‘C:/Users/Erik/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘rms’

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/rms_4.3-0.zip'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/rms_4.3-0.zip'
Warning in install.packages :
  download of package ‘rms’ failed
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/Hmisc_3.15-0.zip'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/Hmisc_3.15-0.zip'
Warning in install.packages :
  download of package ‘Hmisc’ failed

When I looked at http://cran.rstudio.com/bin/windows/contrib/3.2 I found that Hmisc_3.16-0.zip exists but was not being referenced. 

When I tried to manually download and install Hmisc_3.16-0.zip I get the following error:
> install.packages(pkgs="C:/Users/Erik/Downloads/Hmisc_3.16-0.zip" , lib="C:/Users/Erik/Documents/R/win-library/3.2")
Warning in install.packages :
  package ‘C:/Users/Erik/Downloads/Hmisc_3.16-0.zip’ is not available (for R version 3.2.0)

**Comment by GitKlip** [comment]
I get a similar issue trying to download and install rms directly
> install.packages(pkgs="C:/Users/Erik/Downloads/rms_4.3-1.zip" , lib="C:/Users/Erik/Documents/R/win-library/3.2")
Warning in install.packages :
  package ‘C:/Users/Erik/Downloads/rms_4.3-1.zip’ is not available (for R version 3.2.0)

**Comment by harrelfe** [comment]
We have tried this on multiple Windows 7 and Mac computers with no problems.  What are differences for R for Windows 8?

**Comment by GitKlip** [comment]
I'm not aware of any differences with R for windows 8.  Looking on the net I'm not seeing many people having problems with it.  I'm still learning R so you probably know better than me, but based on the errors it seems like there might be two potential issues.

1)  the package dependencies seem a bit off since the install command was looking for a version that didn't exist in the 3.2 directory. are there separate dependency definitions for Windows 7 vs windows 8? 
Package install looked for and couldn't find: 'http://cran.rstudio.com/bin/windows/contrib/3.2/Hmisc_3.15-0.zip'
A different version does exists when I browse the link: 'http://cran.rstudio.com/bin/windows/contrib/3.2/Hmisc_3.16-0.zip'

2) message "/rms_4.3-1.zip’ is not available (for R version 3.2.0)" seems to indicate that there's something needed when building the packages to specify that they work with R 3.2.0

OS: Windows 8.1 64bit
R Version: 3.2.0 (2015-04-16)  x86_64-w64-mingw32 (64bit)
RStudio Version: 0.98.1091 (I think 64bit)
no .Rprofile defined

**Comment by harrelfe** [comment]
The only experience I have with those issues are that I had to make sure I was using the latest version of R and the latest version of RStudio so that install.packages would install the very latest Hmisc.

**Comment by GitKlip** [comment]
Just updated my version of RStudio to the latest and that seems to have fixed it.  Interesting since I only installed my original RStudio about 2 weeks ago :-)  Thanks for your help

**Comment by SteveM49** [comment]
I am trying to get to this package now with R version 3.2.2 (2015-08-14).  I updated RStudio to Version 0.99.473.  I get the warning: package ‘F:/Temp/Hmisc_3.16-0.zip’ is not available (for R version 3.2.2).

Is there something else I should do?

**Comment by ckeraman** [comment]
@GitKlip I am having exactly the same issue on Windows 10, same error messages and ultimately the installation fails.

**Comment by harrelfe** [comment]
With no details there is nothing I can do, and I don't understand why this
is not showing as an issue on Github.

------------------------------
Frank E Harrell Jr      Professor and Chairman      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*

**Comment by 3-1415926535** [comment]
I was finally able to install Hmisc after installing each package noted in the error, e.g., installing rpart when ```install.packages("Hmisc")``` returned:
```
Error : package ‘rpart’ was built before R 3.0.0: please re-install it
ERROR: lazy loading failed for package ‘Hmisc’
* removing ‘/home/wes/R/i686-pc-linux-gnu-library/3.2/Hmisc’
Warning in install.packages :
  installation of package ‘Hmisc’ had non-zero exit status
```
If installing rpart failed because _it_ had out-of-date dependencies, I'd load them then try to reinstall rpart.

If the details of the particular maze I followed and the place I embarked from help:

- This was a fresh install of RStudio Version 0.99.903 on a 34-bit GNU/Linux OS
- Were I to have known all the packages to install and the order to do so, the R command would've been:
```
install.packages("rpart", "nnet", "cluster", "scales", "colorspace", "munsell", "scales", "ggplot2", "latticeExtras", "RColorBrewer", "survival", "Matrix", "lavaan")
```
HTH
