### ISSUE TITLE
R-3.2.1

### ISSUE THREAD

**Issue by Puma-R** [harrelfe/Hmisc#27]
When I attempt to load Hmisc in R=3.2.1, I receive an error message that ggplot2 cannot be loaded.  Apparently, ggplot is a dependency but not all the parts are there.

**Comment by harrelfe** [comment]
People who have had this problem either use RStudio and haven't updated RStudio to the very latest version, or use a Mac and haven't updated ggplot2 to the very latest version.  if you use Mac and have not updated your OS in a while you may also need to update the OS in order to update base R.

**Comment by Puma-R** [comment]
I am using Tinn-R and I have the latest version.  I use Windows.


Respectfully,

Frank Lawrence

**Comment by harrelfe** [comment]
Please provide the version of Hmisc, grid, and ggplot2 and R that you have installed.  Also make sure this fails outside of Tinn-R.

**Comment by Puma-R** [comment]
this is the error message when I try to load Hmisc in R3.2.1 outside Tinn-R:
> library(Hmisc)
Loading required package: grid
Loading required package: lattice
Loading required package: survival
Loading required package: Formula
Loading required package: ggplot2
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
:
  there is no package called ‘munsell’
Error: package ‘ggplot2’ could not be loaded

ggplot2 Version: 1.0.1
grid Version: 3.2.1
Hmisc Version: 3.16-0



Respectfully,

Frank Lawrence

**Comment by harrelfe** [comment]
Thanks.  On my Linux system, the munsell package was automatically installed when I installed ggplot2 and other packages.  Try forcing an install of the munsell package on your system and see what happens.

**Comment by Puma-R** [comment]
Thanks for your help.  That worked.


Respectfully,

Frank Lawrence
