### ISSUE TITLE
Error in minor.tick caused by no non-missing arguments to max

### ISSUE THREAD

**Issue by earlbellinger** [harrelfe/Hmisc#28]
I have encountered an error that I detailed in [this stackoverflow post](http://stackoverflow.com/questions/31478647/floating-point-difficulties-in-r-and-in-particular-in-hmiscs-minor-tick). For the posterity of this issue, I will repeat it here: 

When I call 

    library(Hmisc)
    plot(...)
    minor.tick(...)

occasionally I'll run into the following error:

    Error in seq.default(low.minor, hi.minor, by = distance.between.minor) : 
      'to' cannot be NA, NaN or infinite
    In addition: Warning message:
    In max(possible.minors[possible.minors <= range[2]]) :
      no non-missing arguments to max; returning -Inf

In `minor.tick` there are the following lines:

    range <- par("usr")[if (w == "x") 1:2 else 3:4]
    tick.pos <- if (w == "x") par("xaxp") else par("yaxp")
    ...
    possible.minors <- tick.pos[2] + (0:100) * distance.between.minor
    hi.minor <- max(possible.minors[possible.minors <= range[2]])

when I print out the values of `possible.minors` and `range[2]`, I see, for example,

`> possible.minors
  [1] 1.20 1.24 1.28 1.32 1.36 1.40 1.44 1.48 1.52 1.56 1.60 1.64 1.68 1.72 1.76
 [16] 1.80 1.84 1.88 1.92 1.96 2.00 2.04 2.08 2.12 2.16 2.20 2.24 2.28 2.32 2.36
 [31] 2.40 2.44 2.48 2.52 2.56 2.60 2.64 2.68 2.72 2.76 2.80 2.84 2.88 2.92 2.96
 [46] 3.00 3.04 3.08 3.12 3.16 3.20 3.24 3.28 3.32 3.36 3.40 3.44 3.48 3.52 3.56
 [61] 3.60 3.64 3.68 3.72 3.76 3.80 3.84 3.88 3.92 3.96 4.00 4.04 4.08 4.12 4.16
 [76] 4.20 4.24 4.28 4.32 4.36 4.40 4.44 4.48 4.52 4.56 4.60 4.64 4.68 4.72 4.76
 [91] 4.80 4.84 4.88 4.92 4.96 5.00 5.04 5.08 5.12 5.16 5.20`

`> range[2]
[1] 1.2`

which ultimately gives us 

    > possible.minors[1]
    [1] 1.2
    > range[2]
    [1] 1.2
    > possible.minors[1] <= range[2]
    [1] FALSE

so 1.2 is not less than or equal to 1.2. Ok, clearly some floating point nonsense going on here. When I print more digits, I find

    > print(possible.minors[1], digits=20)
    [1] 1.2000000000000001776
    > print(range[2], digits=20)
    [1] 1.1999999999999999556

it seems that the author of this package anticipated this, because the next line checks whether the result is NA, and if so, assigns a value. Maybe this worked in previous versions of R, but it seems now to cause the package to crash. In any case, I think the correct way is to check if there are any values such that the inequality holds, and if so pick the max, and if not then do the other thing.

**Comment by earlbellinger** [comment]
To be more specific, the quick solution is 

    minor.tick <- function (nx = 2, ny = 2, tick.ratio = 0.5) 
    {
        ax <- function(w, n, tick.ratio) {
            range <- par("usr")[if (w == "x") 
                1:2
            else 3:4]
            tick.pos <- if (w == "x") 
                par("xaxp")
            else par("yaxp")
            distance.between.minor <- (tick.pos[2] - tick.pos[1])/tick.pos[3]/n
            possible.minors <- tick.pos[1] - (0:100) * distance.between.minor
            low.minor <- min(possible.minors[possible.minors >= range[1]])
            if (is.na(low.minor) || is.infinite(low.minor))
                low.minor <- tick.pos[1]
            possible.minors <- tick.pos[2] + (0:100) * distance.between.minor
            hi.minor <- max(possible.minors[possible.minors <= range[2]])
            if (is.na(hi.minor) || is.infinite(hi.minor))
                hi.minor <- tick.pos[2]
            axis(if (w == "x") 
                1
            else 2, seq(low.minor, hi.minor, by = distance.between.minor), 
                labels = FALSE, tcl = par("tcl") * tick.ratio)
        }
        if (nx > 1) 
            ax("x", nx, tick.ratio = tick.ratio)
        if (ny > 1) 
            ax("y", ny, tick.ratio = tick.ratio)
        invisible()
    }

and, in my opinion, a better solution is 

    minor.tick <- function (nx = 2, ny = 2, tick.ratio = 0.5) 
    {
        ax <- function(w, n, tick.ratio) {
            range <- par("usr")[if (w == "x") 
                1:2
            else 3:4]
            tick.pos <- if (w == "x") 
                par("xaxp")
            else par("yaxp")
            distance.between.minor <- (tick.pos[2] - tick.pos[1])/tick.pos[3]/n
            possible.minors <- tick.pos[1] - (0:100) * distance.between.minor
            low.candidates <- possible.minors >= range[1]
            low.minor <- if (any(low.candidates)) {
                min(possible.minors[low.candidates])
            } else {
                tick.pos[1]
            }
            possible.minors <- tick.pos[2] + (0:100) * distance.between.minor
            hi.candidates <- possible.minors <= range[2]
            hi.minor <- if (any(hi.candidates)) {
                max(possible.minors[hi.candidates])
            } else {
                tick.pos[2]
            }
            axis(if (w == "x") 
                1
            else 2, seq(low.minor, hi.minor, by = distance.between.minor), 
                labels = FALSE, tcl = par("tcl") * tick.ratio)
        }
        if (nx > 1) 
            ax("x", nx, tick.ratio = tick.ratio)
        if (ny > 1) 
            ax("y", ny, tick.ratio = tick.ratio)
        invisible()
    }

which avoids all warnings.

**Comment by harrelfe** [comment]
I've replaced minor.tick with the revised version from Earl and have added Earl as an author of the function in the help file.  Earl if you want me to list your affiliation and/or email address in the help file please send them to me.  Thanks for the nice work.  This will be in the next release.

**Comment by earlbellinger** [comment]
Thanks Prof. Harrell, and thanks for the great package. You can put my affiliation as Max Planck Institute, and my email as earlbellinger@gmail.com .

**Comment by harrelfe** [comment]
Thanks - done

Frank E Harrell Jr, PhD
Chairman, Department of Biostatistics

________________________________
