### ISSUE TITLE
Hmisc package to calculate FDR and adjust p-values for multiple correction?

### ISSUE THREAD

**Issue by minisciencegirl** [harrelfe/Hmisc#32]
Does Hmisc adjust p-values for multiple correction?

**Comment by harrelfe** [comment]
No, and I believe that P-value adjustments are overdone.  If you use 
likelihood or Bayesian inference no such adjustments are needed.

On 11/10/2015 05:14 PM, Amy Lee wrote:
>
> Does Hmisc adjust p-values for multiple correction?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/harrelfe/Hmisc/issues/32>.
>

-- 
------------------------------------------------------------------------
Frank E Harrell Jr 	Professor and Chairman 	School of Medicine

	Department of *Biostatistics* 	*Vanderbilt University*
