### ISSUE TITLE
Error using mdb.get

### ISSUE THREAD

**Issue by jbryer** [harrelfe/Hmisc#34]
I get the following error using mdb.get on Mac:

```
Can't alloc filename
```

Looking at the source code on line 26 of `mdb.get.s` you add a `-b strip` parameter. That is not a valid parameter for `mdb-export` on my installation (see `man mdb-export`). I suggest changing it to:

```
system(paste0("mdb-export '", normalizePath(file), "' ", shQuote(tab), " > ", f))
```

This works for me but may cause issues if there are blobs in the table. Could probably add checking afterwards. I don't have an Access file with blogs to try it.

**Comment by harrelfe** [comment]
For the next release (and already committed in github) you can add the argument mdbexportArgs='' to the call to nullify -b strip.

**Comment by jbryer** [comment]
Thanks.
