### ISSUE TITLE
summary table issue with new version of R (3.2.3)

### ISSUE THREAD

**Issue by jeffzs** [harrelfe/Hmisc#39]
Using the newest Hmisc build (3.17-1) and R 3.2.3, I am having trouble with the summaryM function displaying 3rd quartile from continuous variables. 

Say for example I want to print variable x that is a continuous variable as just Q1/median/Q3, now in the latest R version it just shows up as Q1/median. 

I was able to work around the issue in 2 ways:
1) if I use the prmsd flag, then Q3 shows up...  as in Q1/median/Q3 mean+/-SD
2) downgrading R back to version 3.2.2

Thank you very much

**Comment by couthcommander** [comment]
That was my fault.  I believe it's fixed in 3.17-2 (on master), but I'll double-check.  Thanks

**Comment by jeffzs** [comment]
Thank you so much. This is one of my most favorite packages! Thanks for the hard work!

**Comment by couthcommander** [comment]
Yes, it's fixed in v3.17-2, available now if you compile from github
