### ISSUE TITLE
Row percentages

### ISSUE THREAD

**Issue by lytopn80** [harrelfe/Hmisc#47]
Hi,

Is there a standard way of returning row percentages instead of column percentages in the summary() function? Thanks.

Stan.

**Comment by harrelfe** [comment]
No.

In future look at the summaryM and other summary* functions.  Those are
being better maintained.

Frank

------------------------------
Frank E Harrell Jr      Professor and Chairman      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*
