### ISSUE TITLE
latexDotchart should check labels argument

### ISSUE THREAD

**Issue by couthcommander** [harrelfe/Hmisc#48]
Not sure if `latexTranslate` is the proper thing to call, but a label like "age_at_event" should have underscores escaped.  Found after a `print.lrm` call.

**Comment by harrelfe** [comment]
Please retry this with the verison of latexTabular that's on git but not
yet on CRAN.


------------------------------
Frank E Harrell Jr      Professor and Chairman      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*

**Comment by couthcommander** [comment]
I believe that's the same issue, but latexDotchart, not latexTabular.  Short example:
`x=rnorm(5); latexDotchart(x, c('a','b','c','d','e_to_z'), x)`

**Comment by harrelfe** [comment]
Fixed and committed.  Thanks.

------------------------------
Frank E Harrell Jr      Professor and Chairman      School of Medicine

Department of *Biostatistics*      *Vanderbilt University*
