### ISSUE TITLE
html() of a summaryM object prints extra backslash when using "what = '%'"

### ISSUE THREAD

**Issue by jenniferthompson** [harrelfe/Hmisc#56]
Call is `html(summaryM(...), what = '%', ...)`. Result looks like:

93\\% 2466⁄2664

(Thanks for all the hard work on the HTML format!!)

**Comment by harrelfe** [comment]
Sorry about that.  The following Linux version fixes the problem: http://data.vanderbilt.edu/fh/attach/Hmisc_4.0-1.tar.gz
