### ISSUE TITLE
Hmisc loading error: survival >= 2.40.1 not found

### ISSUE THREAD

**Issue by DominiqueMakowski** [harrelfe/Hmisc#57]
My Travis CI package build fails and returns me the following reason:
```
Error : package ‘survival’ 2.39.4 was found, but >= 2.40.1 is required by ‘Hmisc’
ERROR: lazy loading failed for package ‘Hmisc’
```
Is the 2.40.1 absolutely necessary? Could we downgrade the requirement?

Thanks,

**Comment by harrelfe** [comment]
Yes it's necessary.  Upgrade survival!
