### ISSUE TITLE
Permission to include "regexpEscape.s" (as R) in userfriendlyscience

### ISSUE THREAD

**Issue by Matherion** [harrelfe/Hmisc#66]
Hey there,

I'd like to include "regexpEscape.s" (as R) in package userfriendlyscience to avoid importing the entire package just for that function. Is that ok?

I kind of assumed it is, so it's currently at https://github.com/Matherion/userfriendlyscience/blob/master/R/escapeRegex_(from_Hmisc).R with a help file at https://github.com/Matherion/userfriendlyscience/blob/master/man/escapeRegex.Rd. The author is also credited at https://github.com/Matherion/userfriendlyscience/blob/master/man/userfriendlyscience-package.Rd.

If it's not ok to include it, or if you'd like me to change the way it's credited, please let me know!

Thank you, kind regards,

Gjalt-Jorn

**Comment by harrelfe** [comment]
This will be fine.  Thanks for asking.  Please give credit for it to Charles Dupont with affiliation listed in the help file.

**Comment by Matherion** [comment]
Great, that's what I did now. Thank you for your positive response!!!
