### ISSUE TITLE
Hmisc not loading with UsingR

### ISSUE THREAD

**Issue by davemc528** [harrelfe/Hmisc#68]
I'm working through Using R for Introductory Statistics, and whenever I try and load the UsingR package I get this error: 
> install.packages("UsingR")
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/UsingR_2.0-5.tgz'
Content type 'application/x-gzip' length 2043639 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

The downloaded binary packages are in
	/var/folders/5q/m7kmn4gs7pq_5yk42ldrckvc0000gn/T//Rtmp6ONqNe/downloaded_packages
> require(UsingR)
Loading required package: UsingR
Loading required package: Hmisc
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘data.table’
Failed with error:  ‘package ‘Hmisc’ could not be loaded’

Any help would be appreciated.

**Comment by couthcommander** [comment]
I'm not the primary maintainer, but I think Hmisc requires the `data.table` package.  Not sure why it wouldn't be installed as well, but try `install.packages('data.table')`.
