### ISSUE TITLE
Is it possible to have only mean and SD without the three quantiles 

### ISSUE THREAD

**Issue by raffdoc** [harrelfe/Hmisc#76]
Hi Prof Harrell
I have asked this question on stackoverflow several years ago, now you have changed in this package many things, and I love the tables made by summarM function. 
Is it possible to print out only mean and SD instead of three quantiles plus mean and sd?
I know your philosophy summarisation, but it can be very helpful and flexible to have only mean and sd, or, even more, to be able to give summarisation functions by ourselves.  
All the best.

**Comment by harrelfe** [comment]
I don't think that is possible, and I'm fairly certain it would not be good statistical practice.
