### ISSUE TITLE
Suppress Ecdf plot

### ISSUE THREAD

**Issue by indrajitsg** [harrelfe/Hmisc#84]
Is there a way to suppress the plot generated when calling the Ecdf function? I just need to generate the coordinates.

**Comment by harrelfe** [comment]
No way to suppress.  Just use the R base function `ecdf` which returns coordinates, I believe.

**Comment by indrajitsg** [comment]
No I need to use this function as it incorporates weights. Thanks anyway. Would you add that option in future release?

**Comment by harrelfe** [comment]
In looking at the code for `Ecdf.default` I see that it already does exactly what you want.  You can specify `pl=FALSE` and the coordinates are already returned invisibly.  So just store the result in an object you can reference.

**Comment by indrajitsg** [comment]
This is perfect. Thanks a lot.
