### ISSUE TITLE
Hmisc 4.1-0 breaks RcmdrMisc

### ISSUE THREAD

**Issue by EddieWQ** [harrelfe/Hmisc#85]
Rcmdr failed to load after update Hmisc to 4.1-0. Error message as follow:
`Loading required package: RcmdrMisc
Error: package or namespace load failed for ‘RcmdrMisc’:
 object ‘print.rcorr’ is not exported by 'namespace:Hmisc'
Error: package ‘RcmdrMisc’ could not be loaded`
Roll back to Hmisc 4.0-3 from CRAN will solve the problem.
my setting: R version 3.4.3 in MacOS 10.13.2 High Sierra

**Comment by harrelfe** [comment]
This has already been addressed by the developer of Rcmdr who has submitted a new version of RcmdrMisc to CRAN
